### ISSUE TITLE
wojcikowski.pl is down

### ISSUE THREAD

**Issue by jaimergp** [oddt/rfscorevs_binary#1]
Hi, I am trying to test this scoring function, but the server is down and, as a result, binaries not accessible, nor the `*.pickle` files. Maybe they can be uploaded as a GitHub release for permanent storage? Thank you, Jaime.

**Comment by mwojcikowski** [comment]
Everything works fine on my end. Could you check if the server resolves correcty? Maybe your DNS fails to do so.

As suggested I have uploaded a [release v1.0](https://github.com/oddt/rfscorevs_binary/releases/tag/1.0) on Github for anyone who cant access the external server.

**Comment by jaimergp** [comment]
I checked on https://downforeveryoneorjustme.com/wojcikowski.pl and it looks like it can't be reached from there either.

This is the output from `ping` and `tracepath`:

```
> ping wojcikowski.pl
PING wojcikowski.pl (176.9.39.36) 56(84) bytes of data.
^C
--- wojcikowski.pl ping statistics ---
10 packets transmitted, 0 received, 100% packet loss, time 134ms


> tracepath wojcikowski.pl 

 1?: [LOCALHOST]                      pmtu 1500
 1:  _gateway                                            106.134ms 
 1:  _gateway                                              3.646ms 
 2:  100.65.130.171                                        1.497ms pmtu 1488
 2:  100.65.128.1                                         57.832ms 
 3:  10.15.0.49                                           58.477ms asymm  6 
 4:  10.15.246.6                                          75.306ms asymm  5 
 5:  10.15.2.14                                           58.104ms 
 6:  ae8-1.mad10.core-backbone.com                        83.450ms asymm  5 
 7:  ae10-2021.fra20.core-backbone.com                    94.367ms asymm  6 
 8:  core-backbone.hetzner.com                            89.358ms asymm  6 
 9:  core22.fsn1.hetzner.com                              95.076ms asymm  8 
10:  ex9k1.dc6.fsn1.hetzner.com                           94.264ms asymm  9 
11:  no reply
12:  no reply
13:  no reply
14:  no reply
15:  no reply
16:  no reply
17:  no reply
18:  no reply
19:  no reply
20:  no reply
21:  no reply
22:  no reply
23:  no reply
24:  no reply
25:  no reply
26:  no reply
27:  no reply
28:  no reply
29:  no reply
30:  no reply
     Too many hops: pmtu 1488
     Resume: pmtu 1488 
```

Hope it helps! And thanks for the upload!

**Comment by jaimergp** [comment]
I do have access from one of my servers. Weird, indeed!

**Comment by mwojcikowski** [comment]
It is the provider's fault - there was a switch issue, they had resolved it, but I guess some caches need to be flushed... As you can see there seem to be a loop on one of Hetzner's switches.

Anyhow, for now we have redundancy on Github Releases. Thanks for the suggestion and detailed information from your network endpoint.

Feel free to close the issue unless there is anything I could do for you.

**Comment by jaimergp** [comment]
That was fast! Thanks a lot!
