### ISSUE TITLE
rf-score-vs start

### ISSUE THREAD

**Issue by amorim89** [oddt/rfscorevs_binary#4]
Hi @mwojcikowski, 

I am trying to use your tool to perform a rescoring of Vina's results, however I am not succeeding. I have ligands with different structures, but the tool generates identical scores values in all cases. Could you help me with a possible answer to the error I might be making?

Thanks

**Comment by mwojcikowski** [comment]
Could you please provide a command and if possible files to reproduce the issue?

**Comment by amorim89** [comment]
rf-score-vs --receptor 5z9p_dock.pdb anthra_subst.sdf -O ligands_5Z9P_rescored.csv

I am sending the pdb and sdf files as txt format

[5z9p_dock.txt](https://github.com/oddt/rfscorevs_binary/files/5533369/5z9p_dock.txt)
[anthra_subst.txt](https://github.com/oddt/rfscorevs_binary/files/5533371/anthra_subst.txt)

**Comment by Jooyun1983** [comment]
> rf-score-vs --receptor 5z9p_dock.pdb anthra_subst.sdf -O ligands_5Z9P_rescored.csv
> 
> I am sending the pdb and sdf files as txt format
> 
> [5z9p_dock.txt](https://github.com/oddt/rfscorevs_binary/files/5533369/5z9p_dock.txt)
> [anthra_subst.txt](https://github.com/oddt/rfscorevs_binary/files/5533371/anthra_subst.txt)

Hi, I confirmed your input data. I think....it is a problem that anthra_subs.txt (*.sdf) were not docked to 5z9p_dock.txt (*.pdb). So, all scores might be identical for all ligands.

**Comment by amorim89** [comment]
Hi @Jooyun1983, thank you very much for your help and attention. 

With the same ligands I got scores that I believe are correct using other targets. My anaconda version is 4.8.3, pyinstaller 3.6, oddt 0.7, all installed on a virtualenv. Only the sklearn-compiledtrees that presented an installation error, but as I said before; for other targets I got results with the same ligands.

Thanks

**Comment by Jooyun1983** [comment]
Thanks, @amorim89 ! I also found another way. I set the python 2.7 // the pyinstaller, sklearn-compiledtrees, and oddt descrived in the binary implementation details and licensing. Further, I run the rf-scire-vs_linux.sh. I hope your problem will be solved, too.

**Comment by amorim89** [comment]
I'm happy for you @Jooyun1983, I need to find another ML strategy to complement my work... I can't install sklearn-compiledtrees, even with different versions of pip, and this may be one of the problems, but I've spent too much time trying... Thanks again for the answer...

**Comment by mwojcikowski** [comment]
@amorim89 When you install compiledtrees make sure you install the latest git version:
```bash
pip install git+https://github.com/ajtulloch/sklearn-compiledtrees.git
```

**Comment by amorim89** [comment]
@mwojcikowski, I keep trying...

**Comment by RJ-Li** [comment]
I encounter this strange issue when I use binary to score a single ligand to its target:
```
`$ ./rf-score-vs --receptor 2020_refined_m0_pocket/1a1e_m0_pocket.pdb 2020_refined_lig_sdf/1a1e_ligand.sdf -o csv --field "name" --field "RFScoreVS_v2"`
Traceback (most recent call last):
  File "rf-score-vs", line 111, in <module>
    
StopIteration
Failed to execute script rf-score-vs
```
I am sure the binary `rf-score-vs` can work, because I run it with test files, it works. @mwojcikowski
